# Generated by Django 4.0.4 on 2022-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ManyToManyField(blank=True, related_name='friend1', to='main.profile')),
                ('friend2', models.ManyToManyField(blank=True, related_name='friend2', to='main.profile')),
            ],
        ),
    ]
