# Generated by Django 4.0.4 on 2022-04-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_friend_options_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
