# Generated by Django 4.0.4 on 2022-04-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend1',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='main.profile'),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend2',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='main.profile'),
        ),
    ]
